---
# Variables para servidores Linux
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

# Usuario por defecto (puede ser sobrescrito por host)
ansible_user: ansible
ansible_become: yes
ansible_become_method: sudo

# Configuraci√≥n de sistema
system_timezone: America/New_York
system_locale: en_US.UTF-8

# Paquetes comunes para todos los Linux
common_packages:
  - vim
  - curl
  - wget
  - git
  - htop
  - net-tools
  - unzip
