---
# Variables para servidores Windows

# Conexi√≥n WinRM
ansible_connection: winrm
ansible_port: 5985  # HTTP (cambiado de 5986)
ansible_winrm_transport: ntlm
ansible_winrm_server_cert_validation: ignore

# Credenciales Windows (usuario fijo, password se pasa por comando)
ansible_user: ansib

# PowerShell configuration
ansible_shell_type: powershell
ansible_winrm_operation_timeout_sec: 60
ansible_winrm_read_timeout_sec: 70

# Windows no usa sudo/become
ansible_become: no

# Chocolatey packages comunes
common_chocolatey_packages:
  - googlechrome
  - 7zip
  - notepadplusplus
  - git
  - putty
